#!/usr/bin/env python3
"""Generate reference ("golden") data for the engine's unit tests.

WHAT THIS IS FOR
----------------
The project's verification standard is that every kernel is checked against an
independent reference implementation. This script produces that reference by running
each operation in PyTorch and writing the inputs together with the expected outputs
into binary files that tests/golden.cpp reads back.

That gives THREE independent implementations of every operation:

    1. PyTorch / NumPy  (this script -> tests/golden/*.bin)
    2. the CPU oracle   (src/cpu_ref/*.cpp)
    3. the CUDA kernel  (kernels/*.cu)

When all three agree, confidence is high. When exactly one disagrees, you know which
one to look at -- which is the real value of having three rather than two. Two
implementations tell you something is wrong; three tell you what.

WHY INPUTS COME FROM NUMPY EVEN ON THE TORCH BACKEND
----------------------------------------------------
Inputs are always generated by NumPy with a fixed seed, and only the *expected
outputs* are computed by the selected backend. So switching backends cannot change
the inputs, which makes the two backends directly comparable and the whole thing
reproducible run to run.

WHY REFERENCES ARE COMPUTED IN FLOAT64
--------------------------------------
The reference should be the most accurate answer available, not merely another
float32 answer. Reductions are done in float64 and the result is cast down to
float32 for storage. This matches the CPU oracle (which accumulates in double) and
means a float32 CUDA kernel is measured against something genuinely better than
itself, rather than against an equally-wrong sibling.

USAGE
-----
    python3 tools/gen_reference.py                  # torch if available, else numpy
    python3 tools/gen_reference.py --backend numpy   # force numpy
    python3 tools/gen_reference.py --out-dir DIR     # default tests/golden
    python3 tools/gen_reference.py --list            # show cases without writing

Output files are generated artifacts and are NOT committed -- see .gitignore. The
script takes about a second, and the build scripts run it for you.
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np

MAGIC = b"ENGREF01"
DTYPE_F32 = 0
SEED = 20260826  # fixed so every run and every machine produces identical inputs


# ---------------------------------------------------------------------------
# Binary writer -- must stay byte-for-byte compatible with tests/golden.cpp
# ---------------------------------------------------------------------------
def write_golden(path: Path, tensors: dict[str, np.ndarray]) -> None:
    """Write a dict of name -> float32 array in the ENGREF01 format."""
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("wb") as f:
        f.write(MAGIC)
        f.write(struct.pack("<i", len(tensors)))

        for name, array in tensors.items():
            arr = np.ascontiguousarray(array, dtype=np.float32)
            name_bytes = name.encode("utf-8")

            f.write(struct.pack("<i", len(name_bytes)))
            f.write(name_bytes)
            f.write(struct.pack("<i", DTYPE_F32))
            f.write(struct.pack("<i", arr.ndim))
            for dim in arr.shape:
                f.write(struct.pack("<q", int(dim)))
            f.write(struct.pack("<q", int(arr.nbytes)))
            f.write(arr.tobytes(order="C"))


# ---------------------------------------------------------------------------
# Reference implementations
#
# Each returns float64 results; the writer casts to float32. The numpy and torch
# paths must agree to within float32 precision -- test_golden checks this indirectly
# by comparing the CPU oracle against whichever backend produced the files.
# ---------------------------------------------------------------------------
class NumpyBackend:
    name = "numpy"

    @staticmethod
    def vector_add(a, b):
        return a.astype(np.float64) + b.astype(np.float64)

    @staticmethod
    def reduce_sum(x):
        return np.array([x.astype(np.float64).sum()])

    @staticmethod
    def softmax_rows(x):
        x64 = x.astype(np.float64)
        m = x64.max(axis=-1, keepdims=True)
        e = np.exp(x64 - m)
        return e / e.sum(axis=-1, keepdims=True)

    @staticmethod
    def rmsnorm(x, weight, eps):
        x64 = x.astype(np.float64)
        mean_sq = np.mean(x64 * x64, axis=-1, keepdims=True)
        out = x64 / np.sqrt(mean_sq + eps)
        if weight is not None:
            out = out * weight.astype(np.float64)
        return out

    @staticmethod
    def matmul(a, b):
        return a.astype(np.float64) @ b.astype(np.float64)

    @staticmethod
    def residual_rmsnorm(x, residual, weight, eps):
        x64 = x.astype(np.float64)
        res64 = residual.astype(np.float64)
        sum64 = x64 + res64
        mean_sq = np.mean(sum64 * sum64, axis=-1, keepdims=True)
        norm = sum64 / np.sqrt(mean_sq + eps)
        if weight is not None:
            norm = norm * weight.astype(np.float64)
        return norm, sum64

    @staticmethod
    def rmsnorm_linear(x, weight, W, eps):
        x64 = x.astype(np.float64)
        mean_sq = np.mean(x64 * x64, axis=-1, keepdims=True)
        temp = x64 / np.sqrt(mean_sq + eps)
        if weight is not None:
            temp = temp * weight.astype(np.float64)
        return temp @ W.astype(np.float64)

    @staticmethod
    def gemv(A, x):
        return x.astype(np.float64) @ A.astype(np.float64)


class TorchBackend:
    name = "torch"

    def __init__(self):
        import torch  # imported lazily so numpy-only environments still work

        self.torch = torch

    def _t(self, x):
        return self.torch.from_numpy(np.ascontiguousarray(x)).to(self.torch.float64)

    def vector_add(self, a, b):
        return (self._t(a) + self._t(b)).numpy()

    def reduce_sum(self, x):
        return self._t(x).sum().reshape(1).numpy()

    def softmax_rows(self, x):
        # torch.softmax already subtracts the max internally, so this is the same
        # numerically stable formulation the oracle uses.
        return self.torch.softmax(self._t(x), dim=-1).numpy()

    def rmsnorm(self, x, weight, eps):
        t = self.torch
        x64 = self._t(x)
        # The reference LLaMA formulation, written out rather than using
        # torch.nn.RMSNorm so it works on older torch versions and so the maths is
        # visible and checkable against src/cpu_ref/rmsnorm_cpu.cpp.
        out = x64 * t.rsqrt(x64.pow(2).mean(-1, keepdim=True) + eps)
        if weight is not None:
            out = out * self._t(weight)
        return out.numpy()

    def matmul(self, a, b):
        return (self._t(a) @ self._t(b)).numpy()

    def residual_rmsnorm(self, x, residual, weight, eps):
        t = self.torch
        x64 = self._t(x)
        res64 = self._t(residual)
        sum64 = x64 + res64
        norm = sum64 * t.rsqrt(sum64.pow(2).mean(-1, keepdim=True) + eps)
        if weight is not None:
            norm = norm * self._t(weight)
        return norm.numpy(), sum64.numpy()

    def rmsnorm_linear(self, x, weight, W, eps):
        t = self.torch
        x64 = self._t(x)
        temp = x64 * t.rsqrt(x64.pow(2).mean(-1, keepdim=True) + eps)
        if weight is not None:
            temp = temp * self._t(weight)
        return (temp @ self._t(W)).numpy()

    def gemv(self, A, x):
        return (self._t(x) @ self._t(A)).numpy()


def select_backend(requested: str):
    if requested == "numpy":
        return NumpyBackend()
    try:
        backend = TorchBackend()
        print(f"backend: torch {backend.torch.__version__}")
        return backend
    except ImportError:
        if requested == "torch":
            print(
                "ERROR: --backend torch requested but PyTorch is not installed.\n"
                "       pip install torch      (or use --backend numpy)",
                file=sys.stderr,
            )
            sys.exit(1)
        print("backend: numpy (PyTorch not installed)")
        print(
            "  NOTE: your project report claims verification against PyTorch.\n"
            "        Install torch on the GPU machine and regenerate before writing\n"
            "        that up, so the claim is literally true."
        )
        return NumpyBackend()


# ---------------------------------------------------------------------------
# Test cases. Shapes are chosen deliberately -- see the comments.
# ---------------------------------------------------------------------------
VECTOR_ADD_SIZES = [1, 31, 32, 33, 255, 256, 257, 4096, 1 << 20]

REDUCE_SUM_SIZES = [1, 31, 32, 33, 255, 256, 257, 4096, 1 << 20]

# (rows, cols)
SOFTMAX_SHAPES = [
    (1, 1),        # degenerate: output must be exactly 1.0
    (1, 1024),
    (128, 127),    # cols not a multiple of 32 -> partial warp in the reduction
    (7, 4096),     # rows not a multiple of anything convenient
    (8, 50257),    # a real GPT-2 vocabulary size: the actual output-projection shape
]

# (rows, cols, with_weight)
RMSNORM_SHAPES = [
    (1, 4096, True),      # LLaMA-7B hidden dim -- the shape that ships
    (128, 4096, True),
    (32, 127, True),      # awkward width
    (32, 4096, False),    # weight == nullptr path
]

# (M, N, K)
MATMUL_SHAPES = [
    (1, 1, 1),
    (32, 32, 32),
    (128, 64, 256),     # all three dims different: catches K/N stride confusion
    (17, 23, 31),       # no dim divisible by any tile size: catches edge padding
    (512, 512, 512),
]

# Module 3 -- (rows, cols, with_weight)
RESIDUAL_RMSNORM_SHAPES = [
    (1, 4096, True),      # Single token
    (128, 4096, True),    # Prefill batch
    (32, 127, True),      # Awkward width
    (32, 4096, False),    # weight == nullptr path
]

# Module 3 -- (M, N, K, with_weight)
RMSNORM_LINEAR_SHAPES = [
    (1, 4096, 4096, True),     # Single-token decode, LLaMA-7B dims
    (32, 4096, 4096, True),    # Small batch
    (1, 12288, 4096, True),    # QKV projection (3 x 4096)
    (17, 127, 31, True),       # Edge-case: nothing divides anything
    (32, 4096, 4096, False),   # weight == nullptr path
]

# GEMV shapes -- (N, K)
GEMV_SHAPES = [
    (4096, 4096),     # Standard decode token projection
    (12288, 4096),    # Wide projection (MLP Gate/Up projection)
    (127, 31),        # Irregular shape (bounds check & alignment test)
    (64, 128),        # Small power of 2
]


def build_cases(rng, backend):
    """Yield (stem, tensors) pairs."""

    # --- vector_add ---------------------------------------------------------
    for n in VECTOR_ADD_SIZES:
        a = rng.standard_normal(n, dtype=np.float32)
        b = rng.standard_normal(n, dtype=np.float32)
        yield f"vector_add__n{n}", {
            "a": a,
            "b": b,
            "expected": backend.vector_add(a, b),
        }

    # --- reduce_sum ---------------------------------------------------------
    for n in REDUCE_SUM_SIZES:
        # Scaled to keep the float32 sum well inside range while still being large
        # enough that a naive float accumulator would visibly drift -- which is the
        # point being tested.
        x = rng.standard_normal(n, dtype=np.float32)
        yield f"reduce_sum__n{n}", {
            "x": x,
            "expected": backend.reduce_sum(x),
        }

    # --- softmax_rows -------------------------------------------------------
    for rows, cols in SOFTMAX_SHAPES:
        x = rng.standard_normal((rows, cols), dtype=np.float32) * 3.0
        yield f"softmax_rows__{rows}x{cols}", {
            "input": x,
            "expected": backend.softmax_rows(x),
        }

    # The adversarial softmax case. Each row targets a specific failure mode:
    #   row 0: all large negative  -> catches a max initialised to 0.0 instead of -inf
    #   row 1: contains +300       -> catches a missing max subtraction (exp overflows)
    #   row 2: all identical       -> every output must be exactly 1/cols
    #   row 3: one huge, rest tiny -> output is ~one-hot; catches sloppy accumulation
    edge = np.zeros((4, 512), dtype=np.float32)
    edge[0, :] = rng.standard_normal(512, dtype=np.float32) - 50.0
    edge[1, :] = rng.standard_normal(512, dtype=np.float32)
    edge[1, 100] = 300.0
    edge[2, :] = 1.5
    edge[3, :] = -20.0
    edge[3, 7] = 20.0
    yield "softmax_rows__edge", {
        "input": edge,
        "expected": backend.softmax_rows(edge),
    }

    # --- rmsnorm ------------------------------------------------------------
    eps = 1e-5
    for rows, cols, with_weight in RMSNORM_SHAPES:
        x = rng.standard_normal((rows, cols), dtype=np.float32)
        tensors = {"input": x}
        weight = None
        if with_weight:
            # Centred near 1.0, as a trained gain parameter actually is.
            weight = (rng.standard_normal(cols, dtype=np.float32) * 0.1 + 1.0)
            tensors["weight"] = weight
        tensors["expected"] = backend.rmsnorm(x, weight, eps)
        suffix = "w" if with_weight else "now"
        yield f"rmsnorm__{rows}x{cols}_{suffix}", tensors

    # An all-zeros row: without eps this is 0/0. The kernel must return zeros,
    # not NaN.
    zeros = np.zeros((2, 256), dtype=np.float32)
    yield "rmsnorm__zeros", {
        "input": zeros,
        "expected": backend.rmsnorm(zeros, None, eps),
    }

    # --- matmul -------------------------------------------------------------
    for m, n, k in MATMUL_SHAPES:
        # Scaled by 1/sqrt(K) so the magnitude of the result stays near 1 regardless
        # of K. Without this, relative-error tolerances would have to change per
        # shape, which would hide real problems at large K.
        scale = 1.0 / np.sqrt(max(k, 1))
        a = (rng.standard_normal((m, k), dtype=np.float32) * scale).astype(np.float32)
        b = (rng.standard_normal((k, n), dtype=np.float32) * scale).astype(np.float32)
        yield f"matmul__{m}x{n}x{k}", {
            "A": a,
            "B": b,
            "expected": backend.matmul(a, b),
        }

    # --- residual_rmsnorm (Exercise 8) --------------------------------------
    for rows, cols, with_weight in RESIDUAL_RMSNORM_SHAPES:
        x = rng.standard_normal((rows, cols), dtype=np.float32)
        res = rng.standard_normal((rows, cols), dtype=np.float32)
        tensors = {"x": x, "residual": res}
        weight = None
        if with_weight:
            weight = (rng.standard_normal(cols, dtype=np.float32) * 0.1 + 1.0)
            tensors["weight"] = weight
        norm_exp, sum_exp = backend.residual_rmsnorm(x, res, weight, eps)
        tensors["expected"] = norm_exp
        tensors["sum_out"] = sum_exp
        suffix = "w" if with_weight else "now"
        yield f"residual_rmsnorm__{rows}x{cols}_{suffix}", tensors

    # zeros case
    zeros_x = np.zeros((2, 256), dtype=np.float32)
    zeros_res = np.zeros((2, 256), dtype=np.float32)
    norm_exp, sum_exp = backend.residual_rmsnorm(zeros_x, zeros_res, None, eps)
    yield "residual_rmsnorm__zeros", {
        "x": zeros_x,
        "residual": zeros_res,
        "expected": norm_exp,
        "sum_out": sum_exp,
    }

    # --- rmsnorm_linear (Exercise 7) ----------------------------------------
    for m, n, k, with_weight in RMSNORM_LINEAR_SHAPES:
        scale_w = 1.0 / np.sqrt(max(k, 1))
        x = rng.standard_normal((m, k), dtype=np.float32)
        W = (rng.standard_normal((k, n), dtype=np.float32) * scale_w).astype(np.float32)
        tensors = {"input": x, "W": W}
        weight = None
        if with_weight:
            weight = (rng.standard_normal(k, dtype=np.float32) * 0.1 + 1.0)
            tensors["weight"] = weight
        tensors["expected"] = backend.rmsnorm_linear(x, weight, W, eps)
        suffix = "w" if with_weight else "now"
        yield f"rmsnorm_linear__{m}x{n}x{k}_{suffix}", tensors

    # --- gemv ---------------------------------------------------------------
    for n, k in GEMV_SHAPES:
        scale_a = 1.0 / np.sqrt(max(k, 1))
        a = (rng.standard_normal((k, n), dtype=np.float32) * scale_a).astype(np.float32)
        x = rng.standard_normal(k, dtype=np.float32)
        yield f"gemv__{n}x{k}", {
            "A": a,
            "x": x,
            "expected": backend.gemv(a, x),
        }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--backend", choices=["auto", "torch", "numpy"], default="auto")
    parser.add_argument("--out-dir", default=None,
                        help="output directory (default: <repo>/tests/golden)")
    parser.add_argument("--list", action="store_true",
                        help="list the cases that would be written, then exit")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    out_dir = Path(args.out_dir) if args.out_dir else repo_root / "tests" / "golden"

    backend = select_backend(args.backend)
    rng = np.random.default_rng(SEED)

    total_bytes = 0
    count = 0

    for stem, tensors in build_cases(rng, backend):
        if args.list:
            shapes = ", ".join(f"{k}{tuple(np.asarray(v).shape)}" for k, v in tensors.items())
            print(f"  {stem}: {shapes}")
            count += 1
            continue

        path = out_dir / f"{stem}.bin"
        write_golden(path, tensors)
        total_bytes += path.stat().st_size
        count += 1

    if args.list:
        print(f"\n{count} case(s)")
        return 0

    print(f"wrote {count} reference file(s) to {out_dir}  "
          f"({total_bytes / 1024 / 1024:.1f} MiB, {backend.name} backend)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
